### ISSUE TITLE
affichage du texte

### ISSUE THREAD

**Issue by yrochat** [maladesimaginaires/intnetviz#10]
L'afficher, rendre possible d'avancer ou reculer, mapper sur un slider.

**Comment by grandjeanmartin** [comment]
Pendant qu'on en discutait, j'ai pris des notes sur nos réflexions "slider" dans le wiki: [Slider](https://github.com/maladesimaginaires/intnetviz/wiki/Réflexions-à-propos-du-ou-des-sliders)

**Comment by axanthos** [comment]
le slider est operationnel (de la façon qu'on avait initialement envisagée)
