### ISSUE TITLE
Revoir choix des couleurs

### ISSUE THREAD

**Issue by yrochat** [maladesimaginaires/intnetviz#21]

**Comment by yrochat** [comment]
Les états seront définis dans une autre issue. À la fin c'est une question de css.
Ma suggestion : Trois niveaux de gris et locuteur en rouge.

**Comment by grandjeanmartin** [comment]
Je suis d'accord concernant la nécessité de n'avoir qu'une seule couleur en plus des tons de gris/noir. J'ajouterais à cette question qu'il serait intéressant d'avoir une bordure dans tous les cas pour les noeuds, pour des questions visuelles/esthétiques. Cette bordure pourrait être systématiquement très fine et d'une couleur très légèrement plus foncée que le fond du noeud, à l'exception du noeud à l'état _previously_activated_ qui aurait une bordure colorée un peu plus large.

**Comment by yrochat** [comment]
Je ne suis pas aussi convaincu que ce soit si nécessaire. La bordure du previously_activated a été évoqué lors de la réunion et je pense que ça pourra être intéressant. On jugera sur pièce.

**Comment by grandjeanmartin** [comment]
oui oui, pas d'urgence, j'ajoutais juste un élément à la discussion puisque tu lançais une suggestion esthétique.

**Comment by yrochat** [comment]
Bons choix d'Aris (pas forcément définitifs) dans son dernier commit.
