### ISSUE TITLE
Grosse issue : comment fait-on pour tomber sur le graphe à n'importe quel step ?

### ISSUE THREAD

**Issue by yrochat** [maladesimaginaires/intnetviz#22]
Est-ce que tous les sous-graphes doivent être pré-processés (dans ce cas c'est lourd) ou peut-on les recalculer (dans ce cas év. problème avec la transition et le calcul on-the-fly)

**Comment by axanthos** [comment]
C'est dans la poche avec le nouveau design modulaire (cf. indexB.html)

**Comment by yrochat** [comment]
OOOOOOOOHHHHHHHH c'est beau.
Quelle est la différence entre index.html et indexB.html ?

**Comment by ipante** [comment]
Congrats Aris! Super beau boulot!

**Comment by axanthos** [comment]
Merci! Tous mes changements sont dans indexB. S'ils vous plaisent, on peut les répercuter dans index et supprimer le B.

**Comment by yrochat** [comment]
Il faut qu'on prenne cette décision avant de recommencer à travailler.

En général, tu peux d'office travailler sur index.html : si tout est cassé
il suffit de revenir à une version qui fonctionne :-)

Le mar. 8 sept. 2015 21:44, Aris Xanthos notifications@github.com a
écrit :

**Comment by ipante** [comment]
J'ai également soumis quelques commits sur indexB.html. Je pense que nous pouvons sans souci copier indexB.html dans index.html et supprimer indexB.html. La version proposée par Aris est supérieure en tous points à la version actuelle. Elle sera aussi nettement plus facile à maintenir.

**Comment by yrochat** [comment]
Voilà, le merge est fait !
Les transitions, quand on déplace le slider, qu'est-ce qu'elles sont belles
:-o
gg
