### ISSUE TITLE
Soumettre à DH2016

### ISSUE THREAD

**Issue by axanthos** [maladesimaginaires/intnetviz#28]
Soumettre un abstract à DH2016, deadline 1er novembre 2015 à minuit GMT, cfp http://dh2016.adho.org/cfp-french/

**Comment by grandjeanmartin** [comment]
Est-ce qu'on lance ici la discussion (sans fin) sur le volet des potentialités pédagogiques ? ou dans un wiki ? ou on garde ça pour nos cafés en attendant d'être plus au clair ?

**Comment by ipante** [comment]
J'en ferais la priorité de notre prochaine rencontre, chacun envisageant différents scénarios de test de son côté. Une page wiki ne serait pas un mal non plus. Mais je pense préférable de sortir de cette issue pour en discuter.

**Comment by yrochat** [comment]
Pour rappel, c'est 1500 mots, que ce soit un short ou un long paper
http://dh2016.adho.org/cfp/ À quatre, ça devrait aller vite.
