### ISSUE TITLE
Problème données Ecole des femmes

### ISSUE THREAD

**Issue by axanthos** [maladesimaginaires/intnetviz#29]
Les répliques 273-285 (environ) ont été mal parsées et devraient être corrigées manuellement (dans les deux fichiers).

**Comment by axanthos** [comment]
C'est pire que je pensais, il y a aussi beaucoup de didascalies mal parsées

**Comment by grandjeanmartin** [comment]
Je vais essayer de faire un inventaire prochainement

**Comment by grandjeanmartin** [comment]
En fait, après premier passage en revue, il y a un problème avec les <didascalie> quand celles-ci sont intégrées à une réplique. Exemple : 
`<l>Phrase 1</l>
<didascalie>À part</didascalie>
<l>Phrase 2</l>`
Elles sont reconnues comme telles, parce que leur balise remplace la balise de ligne, mais elles ne sont pas envoyées dans la colonne "didascalie".

**Comment by grandjeanmartin** [comment]
Parfois il y a plusieurs didascalie dans une réplique. Conséquence de notre système : si on les met dans une colonne séparée, on ne sait plus à quel morceau de la réplique elle s'applique (enfin, c'est pour l'instant un moindre mal).

**Comment by grandjeanmartin** [comment]
(je sépare donc l'issue #29 qui consiste à nettoyer le fichier pour que le texte soit propre de l'issue #37 qui consiste à trouver une solution pour l'affichage des didascalies complexes)

**Comment by grandjeanmartin** [comment]
Rapport: il y avait 39 répliques avec didascalies mal parsées (parfois plusieurs par répliques).

**Comment by grandjeanmartin** [comment]
Voilà, suite au nettoyage de Acte III scènes II, II et IV, 9 répliques ont été enlevées et 1 ajoutées (passage de 566 à 558 répliques, au total)

**Comment by yrochat** [comment]
Merci beaucoup ! N'oublie pas de commiter tout ça ;-)

**Comment by grandjeanmartin** [comment]
Voilà, pfiu! j'espère que j'ai fait ça correctement ;) #firsttimer

**Comment by axanthos** [comment]
A part le problème des "maximes du mariage", as-tu pu identifier la particularité des répliques et diascalies incorrectement parsées et que tu as du ajouter/supprimer?

**Comment by grandjeanmartin** [comment]
Est-ce que tu pourrais me redonner le chemin vers la version originale du texte que tu as fait tourner dans Textable ? Ca m'a manqué pendant le nettoyage et je me demande si je ne pourrais pas y voir plus clairement ces (ir)régularités.

**Comment by axanthos** [comment]
https://www.gutenberg.org/files/43535/43535-0.txt (si je ne m'abuse!)

**Comment by grandjeanmartin** [comment]
Merci (je remets le lien ici, pour archivage: http://www.gutenberg.org/files/43535/43535-h/43535-h.htm#ch3 parce qu'avec le https ça ne passait pas chez moi)

**Comment by grandjeanmartin** [comment]
Donc, j'ai corrigé les corrections (didascalies reportées à tort dans la colonne du même nom) en remettant les lignes corrigées à leur ancienne place, tout en gardant évidemment les corrections "de fond" du passage des Maximes et de la réplique manquante qui la suivait. 
Et j'ai repassé toute la pièce avec les 2 documents en parallèle (le texte original et notre fichier).
- **Acte II Scène II** une réplique d'Arnolphe manquante, contenant plusieurs didascalies.
- **Acte III Scène IV** une réplique d'Horace manquante, c'est la lecture de la lettre attachée à la pierre envoyée par Agnès. Format spécial, ce n'est qu'une seule très très longue ligne.
- **Acte V Scène VII** une didascalie ("Horace et Arnolphe se retirent dans un coin du théâtre, et parlent bas ensemble.") intervient avant la première réplique, ce qui signifie qu'il n'y a pas de place pour elle ni dans le texte ni dans la colonne didascalie, déjà occupée par la didascalie du premier personnage. Pour l'instant, ce n'est pas forcément un problème, si ce n'est qu'elle apparaîtra pas à l'affichage tant qu'on ne lui donne pas un statut.
- **Acte V Scène X** une didascalie "None" enlevée dans la colonne du même nom (probablement liée à la fin du traitement du fichier).

Voilà, je commit les nouvelles version (renumérotation des répliques nécessaire) tout de suite. Au moins, maintenant je connais la pièce par coeur ;-)

**Comment by axanthos** [comment]
Merci, et encore désolé pour le temps perdu!

**Comment by axanthos** [comment]
La fermeture de cette issue résultait d'une fausse manipulation de ma part. Je la ré-ouvre, car des points soulevés dans le dernier message de Martin doivent encore être discutés.

**Comment by grandjeanmartin** [comment]
D'accord. Je signale juste que je proposais de garder cette issue pour les questions pratiques liées à la correction des erreurs que tu signalais, et de passer sur l'issue #37 pour évoquer les questions, à plus long terme, liées aux différents statuts des didascalies. Mais tu as raison, il y a peut-être encore des choses à régler pour liquider la question de la correction. D'ailleurs, faut-il supprimer les fichiers "faux" de notre répertoire (ou les bouger ailleurs)? (edit: pardon, je vois que tu viens de faire ce nettoyage)

**Comment by axanthos** [comment]
D'accord avec toi. A l'occasion, pourrais-tu stp indiquer pour les deux cas qui relèvent, je crois, de cette issue (i.e. Acte II scène II et Acte III scène IV), le numéro de réplique concerné? Le 3è cas devrait sans doute être discuté en #37, et le 4è a été réglé dans une nouvelle version du workflow textable.
