### ISSUE TITLE
Externaliser les codes de couleurs autant que possible vers le .css

### ISSUE THREAD

**Issue by yrochat** [maladesimaginaires/intnetviz#32]

**Comment by ipante** [comment]
Ai tenté dans une branche dédiée de passer par un "attr("class", etc.)" pour factoriser le CSS. Apparemment, D3.js n'aime pas ça. Je vais faire encore quelques tentatives avant de simplement ramener les codes couleurs à des variables.

**Comment by ipante** [comment]
A ce stade, on se limitera à des variables. Une version plus modulaire est possible avec le code suivant:

`case 'not_yet_activated': return eval('color_'+'not_yet_activated');`

Mais cette solution introduit un eval() déconseillé (risque d'injection) et pourrait ralentir le code.
