### ISSUE TITLE
Naviguer de scène en scène et d'acte en acte

### ISSUE THREAD

**Issue by ipante** [maladesimaginaires/intnetviz#35]
Il serait intéressant de pouvoir naviguer de scène en scène ou d'acte en acte, soit :
1. via le slider (qui pourrait contenir des graduations informantes et "aimantées")
2. via des champs interactifs dans le listing (Acte X, Scène X, Réplique X)
3. via des combinaisons de touches (CTRL+flèche droite = Scène, SHIFT+flèche droite = Acte), etc.

A noter que ces différentes approches pourraient être combinées (power-user et user-lambda (1 et 3 ou 2 et 3). Elles permettraient de naviguer plus aisément dans le découpage narratif et de contraster l'évolution d'une scène à l'autre.

Aris, indépendamment de "current_line", a-t-on quelque chose qui nous permette de nous saisir de ces unités structurelles? Sinon, je pense qu'il serait intéressant de les générer.

Qu'en dites-vous?

**Comment by axanthos** [comment]
De bonnes idées! Pour la réplique current_line, les infos sont stockées dans dataset.lines[current_line].piece, dataset.lines[current_line].acte, dataset.lines[current_line].scene et dataset.lines[current_line].replique, mais pour l'heure il n'y a pas, je crois, de façon d'y accéder indépendamment de "current_line".

**Comment by ipante** [comment]
Oui, j'ai fait un test avec ces écritures tout à l'heure, mais impossible de les traiter numériquement (un +1 retourne un légitime NaN). On trouvera quelque chose.

**Comment by axanthos** [comment]
Si j'avais la possibilité d'y travailler, je partirais sur cette voie, dans import_play_data(), avant le traitement des noeuds et arêtes:

1) Initialisation: création des variables _actes_ et _scenes_
2) Boucle sur les répliques _k_:
--- 2.1) Si nouvel acte (_if dataset.lines[k].acte in actes_):
------- 2.1.1) mémoriser num de première réplique (_actes[dataset.lines[k].acte] = parseInt(dataset.lines[k].replique - 1)_) // -1 car les répliques sont numérotées depuis 1 dans le fichier
--- 2.2) Idem si nouvelle scène
...
3) ajouter _actes_ et _scenes_ dans _dataset_ pour y avoir accès depuis le reste du script.

On obtiendrait ainsi pour _actes_ quelque chose comme {"I": 1, "II": 254, ... }, ce qui devrait permettre de peupler assez facilement des <select> en lieu et place des chaînes actuellement utilisées pour indiquer ces informations. Ne pas oublier d'ajouter le code pour fixer leur valeur dans update_display() (toujours à la place des chaînes, donc).

Les graduations seraient chouettes, mais c'est un projet plus ambitieux!

**Comment by axanthos** [comment]
ah et ajouter *actes* et *scenes* dans *dataset* pour y avoir accès depuis le reste du script.

**Comment by ipante** [comment]
Ça me semble une bonne manière de procéder. Laissons peut-être passer la rentrée. Il y a une bonne quantité de chats à fouetter avant ça.

**Comment by ipante** [comment]
C'est fait! Codé à la force de mes petites mains! :)
