### ISSUE TITLE
Affichage des didascalies multiples

### ISSUE THREAD

**Issue by grandjeanmartin** [maladesimaginaires/intnetviz#37]
Pour l'instant, notre gestion des données ne permet pas de marquer le lieu d'apparition d'une didascalie avec précision quand elle est intégrée dans une réplique qui fait plusieurs lignes et quand il y en a plusieurs par répliques.
Suite à mon nettoyage (issue #29), toutes les didascalies d'une réplique sont regroupées dans la même cellule de la colonne "didascalie", séparées par des points-virgules (on perd donc son ancrage dans le texte, mais c'est le seul moyen rapide de pouvoir avoir un texte propre pour notre Beta).

**Comment by grandjeanmartin** [comment]
Il y a un sous-problème avec cette question de didascalie positionnée en pleine réplique : parfois, elle modifie les personnes qui reçoivent une partie de la réplique (du genre "À Alain et Georgette"), ce qui peut peut-être modifier le réseau des personnages...

**Comment by axanthos** [comment]
Merci beaucoup pour ce boulot! Désolé de ne réagir que maintenant. 

En fait je crois que le traitement des didascalies "en ligne" était ok (du moins celles qui étaient correctement parsées): on veut, je crois, les voir dans le texte affiché, à l'endroit où elles apparaissent, ce qui était bien le cas; et dans le cas contraire, on peut dans le code dire "ne pas les afficher" à la place de "les italiciser".

Cela dit les cas que tu mentionnes ("à part", ou "à Alain et Georgette") sont très intéressants et devraient à mon avis donner lieu à la création (manuelle) de nouvelles répliques avec des destinataires différents du reste de la scène (voire pas de destinataires, dans le premier cas).

**Comment by grandjeanmartin** [comment]
Flûte, du coup j'ai appauvri le corpus en mettant ces didascalies dans une colonne séparée (je n'ai pas pensé que les balises <didascalie> pouvaient être utilisée dans l'affichage final et que ce n'était pas ce que tu identifiais comme problématique dans la description de l'issue #29).

**Comment by axanthos** [comment]
Désolé, je vois maintenant que mon commentaire n'était pas du tout assez explicite! A tel point que je ne retrouve pas facilement les "didascalies mal parsées" initialement mentionnées. Sur les 39 que tu as dénombrées, n'y avait-il que des didascalies "en ligne" que tu as placées "hors ligne", ou d'autres problèmes aussi, en particulier des didascalies que Textable n'avait pas identifiées du tout?

**Comment by grandjeanmartin** [comment]
Non, pas de didascalies non identifiées (je relis le texte, je n'en vois pas, à première vue). La confusion vient en partie de l'existence même de cette colonne "didascalie" qui n'a pas vraiment lieu d'être si on considère que les didascalies doivent être affichées dans le texte (mais je comprends bien son utilité puisque les didascalies qui sont couplées au nom du locuteur ne sont pas techniquement dans le texte)... 😕
Je propose que nous continuions la discussion sur ce bug dans l'issue #29, c'est sa place, et que nous gardions ce fil #37 pour discuter des statuts multiples de didascalies "en ligne", "hors ligne", de leur implication sur le réseau et de la nécessité (ou pas) de scinder des répliques en plusieurs morceaux.
