### ISSUE TITLE
Personnages présents dans une scène

### ISSUE THREAD

**Issue by yrochat** [maladesimaginaires/intnetviz#4]
Voir [discussion ici](https://github.com/maladesimaginaires/intnetviz/wiki/Premier-essai-de-pr%C3%A9traitement-avec-l'Ecole-des-femmes#b-fichier-_personnagestab).

**Comment by axanthos** [comment]
Le nouveau schéma Textable se base sur l'énumération en début de scène. (La question des didascalies reste à prendre en compte, au moins manuellement.)
