### ISSUE TITLE
Gif animée

### ISSUE THREAD

**Issue by axanthos** [maladesimaginaires/intnetviz#41]
Creer une animation complète et poster sur github

**Comment by grandjeanmartin** [comment]
Comment est-ce qu'on poste des images sur github, d'ailleurs ?

**Comment by yrochat** [comment]
Tu peux prendre exemple sur ce que j'ai fait hier en glissant l'image dans
le dossier img créé pour l'occasion.

Le gif est déjà prêt, d'ailleurs. Je vais l'uploader.

Le mer. 28 oct. 2015 à 10:31, Martin Grandjean notifications@github.com a
écrit :

**Comment by yrochat** [comment]
Ok c'est fait.

Par contre le gif n'est plus accordé avec la démo pimpée :-/

Le mer. 28 oct. 2015 à 10:41, Yannick Rochat yannick.rochat@gmail.com a
écrit :

**Comment by grandjeanmartin** [comment]
Oui, t'inquiètes, j'avais retourné dans tous les sens ton dossier img et ton image pour essayer de comprendre, mais le glissé-déposé ne fonctionnait pas chez moi, probablement une question de navigateur ou de machine.
Tant mieux si tu as produit le gif, moi j'en étais à en faire une vidéo.

**Comment by yrochat** [comment]
C'est Isaac qui a produit le gif. La page d'accueil est mise à jour, mais
on devra encore la faire évoluer, voir penser à en extraire un site web
facile à la https://pages.github.com/

Le mer. 28 oct. 2015 à 10:50, Martin Grandjean notifications@github.com a
écrit :
