### ISSUE TITLE
Finalisation du papier

### ISSUE THREAD

**Issue by yrochat** [maladesimaginaires/intnetviz#47]
Vendredi 30 octobre 14h15 @ Anthropole

**Comment by grandjeanmartin** [comment]
Ah ah

---

Martin GRANDJEAN
UNIL | Université de Lausanne
martingrandjean.chhttp://www.martingrandjean.ch/

---

Martin GRANDJEAN
UNIL | Université de Lausanne
martingrandjean.chhttp://www.martingrandjean.ch/

Le 27 oct. 2015 à 15:34, Yannick Rochat <notifications@github.com<mailto:notifications@github.com>> a écrit :

Assigned #47https://github.com/maladesimaginaires/intnetviz/issues/47 to @grandjeanmartinhttps://github.com/grandjeanmartin.
