### ISSUE TITLE
Références non standard

### ISSUE THREAD

**Issue by axanthos** [maladesimaginaires/intnetviz#54]
Que faire avec des parties de texte qui échappent à notre indexation en Acte-Scène-Réplique, p.ex. les Prologues et Intermèdes du Malade imaginaire?

**Comment by grandjeanmartin** [comment]
et toute la tragédie grecque (malgré l'apparent anachronisme, il y en a dans notre répertoire de pièces classiques en HTML), ainsi que les pièces qui n'ont qu'un seul acte (qui n'est donc pas noté, et du coup pas reconnu comme tel).
