### ISSUE TITLE
laisser la possibilité à l'utilisateur de déplacer les noeuds?

### ISSUE THREAD

**Issue by axanthos** [maladesimaginaires/intnetviz#64]
Le positionnement obtenu par force layout est parfois peu heureux, voire illisible.

**Comment by yrochat** [comment]
Aussi permettre à l'utilisateur de modifier l'affichage : 
1. modifier divers réglages du layout
2. changer la résolution ?
3. etc.

**Comment by yrochat** [comment]
Résolu le 24 mai à huit mains mais surtout par Isaac.
Pour les calculs de layouts, encore du travail à faire sur les paramètres. 
Je crée une nouvelle issue.
