### ISSUE TITLE
Affichage des titres de scènes (et actes)

### ISSUE THREAD

**Issue by yrochat** [maladesimaginaires/intnetviz#65]
Les annonces de scènes et actes devraient être séparées des répliques.
Solutions possibles : 
1. Une ligne horizontale avec la scène, e.g. "------------ Scène III ------------"
2. Une boîte ne contenant que la mention de la scène. Ne doit pas compter comme réplique.

**Comment by ipante** [comment]
@axanthos @grandjeanmartin @yrochat Voulez-vous maintenir cette fonctionnalité? Avec le nombre d'indications disponibles (graduations et déplacement par actes et par scènes), je pense que l'on devrait pouvoir s'en passer.
