### ISSUE TITLE
Répliques manquantes sur le graphe

### ISSUE THREAD

**Issue by ipante** [maladesimaginaires/intnetviz#71]
Dans les malades imaginaires, les répliques 14 à 50 n'apparaissent pas sur le graphe.

**Comment by grandjeanmartin** [comment]
oui oui, tout le fichier des malades imaginaires est en train d'être corrigé (ce ne sont pas les seules répliques à ne pas s'afficher correctement).

**Comment by grandjeanmartin** [comment]
Inclus dans #67
