### ISSUE TITLE
Mettre en évidence le bouton play/pause

### ISSUE THREAD

**Issue by grandjeanmartin** [maladesimaginaires/intnetviz#81]
Il est à sa place dans la barre, mais ce serait bien de faire comprendre à l'internaute que ce bouton est (le plus) important. Bordure en gras ? Couleur de fond ? etc.

**Comment by yrochat** [comment]
Après discussion, il faudrait qu'il attire le regard (sans forcément être dans un style différent).

Par exemple, le bouton pourrait clignoter 3x mais pas plus longtemps en vert ou orange au moment du chargement de la page.
