### ISSUE TITLE
taille des boutons (Scene +1/-1 légèrement trop grand)

### ISSUE THREAD

**Issue by axanthos** [maladesimaginaires/intnetviz#94]

**Comment by grandjeanmartin** [comment]
Oui, c'est un problème sur Firefox. Et sur Chrome, c'est souvent le bouton End qui saute d'une ligne. Les 2 problèmes peuvent être réglés indépendamment, il me semble : baisser d'1pt la taille du texte corrige Firefox, et baisser d'1px la taille des boutons corrige Chrome (mais dans ce 2e cas, la barre des boutons devient un tout petit peu plus courte que la zone de graphe, ce qui est assez moche - mais nécessaire ?)

**Comment by grandjeanmartin** [comment]
Dans l'immédiat, parce que je préfère avoir un truc moyennement aligné qu'un bouton qui saute complètement, je mets à jour le styles.css selon mon commentaire ci-dessous.
